### ISSUE TITLE
Injecting a constant or dynamic value

### ISSUE THREAD

**Issue by jamarzka** [wessberg/DI#2]
Do you have any plans to add support for injecting constant or dynamic values at runtime?

https://github.com/inversify/InversifyJS/blob/master/wiki/value_injection.md

**Comment by wessberg** [comment]
You can inject *singletons* and *transients*.

*Singletons* always will inject the same instance (e.g. "constant values") whereas *transients* will always instantiate a new service (e.g. "dynamic values")  or re-evaluate the given callback and return some value and use that as the service). If I understand your question correctly, I think the following piece of code would suit your use case:

```typescript
const container = new DIContainer();
container.registerTransient<IMyInterface>(() => something);
```

**Comment by jamarzka** [comment]
That works! Thanks
